wrapperVersion=3.3.4
distributionType=bin
distributionUrl=https://maven.aliyun.com/repository/central/org/apache/maven/apache-maven/3.9.14/apache-maven-3.9.14-bin.zip
wrapperUrl=https://maven.aliyun.com/repository/central/org/apache/maven/wrapper/maven-wrapper/3.3.4/maven-wrapper-3.3.4.jar
