server:
  port: 8080 # ???????

spring:
  application:
    name: forklift-erp # ????????Initializr??????
  datasource:
    url: jdbc:mysql://localhost:3306/forklift_erp?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root # ???????????
    password: ChH060118 # ??????????
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update # ??: ????Entity????????????????????????none?validate
    show-sql: true # ??????SQL???????
    properties:
      hibernate:
        format_sql: true # ??????SQL
    database-platform: org.hibernate.dialect.MySQL8Dialect # ???????

# ????
logging:
  level:
    com.example.forklift_erp: debug # ???????????debug?????