CREATE TABLE IF NOT EXISTS supplier_profile (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    supplier_name VARCHAR(120) NOT NULL,
    supplier_type VARCHAR(50),
    contact_name VARCHAR(80),
    contact_phone VARCHAR(50),
    address VARCHAR(255),
    tax_number VARCHAR(100),
    bank_account VARCHAR(120),
    remarks VARCHAR(500),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    last_modified_by VARCHAR(50),
    last_modified_role VARCHAR(30),
    last_modified_priority INT DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_supplier_profile_name (supplier_name),
    KEY idx_supplier_profile_type (supplier_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS purchase_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    purchase_no VARCHAR(80) NOT NULL,
    supplier_id BIGINT,
    supplier_name VARCHAR(120),
    config_item_id BIGINT,
    config_value_id BIGINT,
    resource_type VARCHAR(30) NOT NULL DEFAULT 'PART',
    resource_code VARCHAR(100),
    resource_name VARCHAR(120),
    specification_model VARCHAR(120),
    quantity INT NOT NULL DEFAULT 1,
    unit VARCHAR(20),
    unit_price DECIMAL(12, 2),
    total_amount DECIMAL(12, 2),
    freight_amount DECIMAL(12, 2) NOT NULL DEFAULT 0,
    order_date DATE,
    expected_arrival_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'ORDERED',
    operator VARCHAR(50),
    remark VARCHAR(500),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    last_modified_by VARCHAR(50),
    last_modified_role VARCHAR(30),
    last_modified_priority INT DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_purchase_order_no (purchase_no),
    KEY idx_purchase_order_supplier (supplier_id),
    KEY idx_purchase_order_config (config_item_id, config_value_id),
    KEY idx_purchase_order_resource (resource_type, resource_code),
    KEY idx_purchase_order_status (status),
    CONSTRAINT fk_purchase_order_supplier
        FOREIGN KEY (supplier_id) REFERENCES supplier_profile (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS stocktaking_record (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    stocktaking_no VARCHAR(80) NOT NULL,
    resource_type VARCHAR(30) NOT NULL,
    resource_id BIGINT,
    resource_code VARCHAR(100),
    resource_name VARCHAR(120),
    specification_model VARCHAR(120),
    book_quantity INT NOT NULL DEFAULT 0,
    actual_quantity INT NOT NULL DEFAULT 0,
    difference_quantity INT NOT NULL DEFAULT 0,
    stocktaking_date DATE,
    status VARCHAR(30) NOT NULL DEFAULT 'DRAFT',
    operator VARCHAR(50),
    remark VARCHAR(500),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    last_modified_by VARCHAR(50),
    last_modified_role VARCHAR(30),
    last_modified_priority INT DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_stocktaking_no (stocktaking_no),
    KEY idx_stocktaking_resource (resource_type, resource_id),
    KEY idx_stocktaking_status (status),
    KEY idx_stocktaking_date (stocktaking_date)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
