CREATE TABLE IF NOT EXISTS resource_attachment (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT,
    resource_type VARCHAR(40) NOT NULL,
    resource_id BIGINT NOT NULL,
    resource_code VARCHAR(100),
    resource_name VARCHAR(120),
    attachment_category VARCHAR(40) NOT NULL,
    attachment_label VARCHAR(120),
    storage_scope VARCHAR(40) NOT NULL DEFAULT 'ATTACHMENT',
    original_name VARCHAR(255) NOT NULL,
    stored_file_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(120),
    file_size BIGINT,
    file_extension VARCHAR(20),
    previewable TINYINT(1) NOT NULL DEFAULT 1,
    upload_note VARCHAR(500),
    uploaded_by VARCHAR(50),
    uploaded_at DATETIME(6),
    deleted TINYINT(1) NOT NULL DEFAULT 0,
    deleted_by VARCHAR(50),
    deleted_at DATETIME(6),
    delete_reason VARCHAR(255),
    PRIMARY KEY (id),
    KEY idx_resource_attachment_resource (resource_type, resource_id, attachment_category, deleted, uploaded_at),
    KEY idx_resource_attachment_uploaded_at (uploaded_at),
    KEY idx_resource_attachment_deleted_at (deleted_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS data_import_job (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT,
    import_type VARCHAR(60) NOT NULL,
    template_name VARCHAR(120),
    original_file_name VARCHAR(255),
    staged_file_name VARCHAR(255),
    status VARCHAR(30) NOT NULL,
    total_rows INT NOT NULL DEFAULT 0,
    valid_rows INT NOT NULL DEFAULT 0,
    error_rows INT NOT NULL DEFAULT 0,
    imported_rows INT NOT NULL DEFAULT 0,
    skipped_rows INT NOT NULL DEFAULT 0,
    summary VARCHAR(1000),
    error_rows_json LONGTEXT,
    validation_snapshot_json LONGTEXT,
    created_by VARCHAR(50),
    imported_by VARCHAR(50),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    started_at DATETIME(6),
    finished_at DATETIME(6),
    PRIMARY KEY (id),
    KEY idx_data_import_job_type_created_at (import_type, created_at),
    KEY idx_data_import_job_status (status),
    KEY idx_data_import_job_imported_at (finished_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
