CREATE TABLE IF NOT EXISTS customer_profile (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    company_name VARCHAR(120) NOT NULL,
    address VARCHAR(255),
    contact_name VARCHAR(80),
    contact_phone VARCHAR(50),
    tax_or_id_number VARCHAR(100),
    remarks VARCHAR(500),
    created_at DATETIME(6),
    updated_at DATETIME(6),
    last_modified_by VARCHAR(50),
    last_modified_role VARCHAR(30),
    last_modified_priority INT DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_customer_profile_company_name (company_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS outbound_order (
    id BIGINT NOT NULL AUTO_INCREMENT,
    version BIGINT NOT NULL DEFAULT 0,
    order_no VARCHAR(80) NOT NULL,
    resource_type VARCHAR(30) NOT NULL,
    resource_id BIGINT,
    resource_code VARCHAR(100),
    resource_name VARCHAR(120),
    specification_model VARCHAR(120),
    quantity INT NOT NULL DEFAULT 1,
    unit VARCHAR(20),
    customer_id BIGINT,
    customer_name VARCHAR(120),
    customer_address VARCHAR(255),
    contact_name VARCHAR(80),
    contact_phone VARCHAR(50),
    tax_or_id_number VARCHAR(100),
    settlement_price DECIMAL(12, 2),
    payment_settled BIT(1) NOT NULL DEFAULT b'0',
    sales_reported BIT(1) NOT NULL DEFAULT b'0',
    invoice_applied BIT(1) NOT NULL DEFAULT b'0',
    sales_report_date DATE,
    invoice_application_date DATE,
    order_remark VARCHAR(500),
    operator VARCHAR(50),
    stock_operation_log_id BIGINT,
    created_at DATETIME(6),
    updated_at DATETIME(6),
    last_modified_by VARCHAR(50),
    last_modified_role VARCHAR(30),
    last_modified_priority INT DEFAULT 0,
    PRIMARY KEY (id),
    UNIQUE KEY uk_outbound_order_no (order_no),
    KEY idx_outbound_order_resource (resource_type, resource_id),
    KEY idx_outbound_order_customer (customer_id),
    KEY idx_outbound_order_created_at (created_at),
    CONSTRAINT fk_outbound_order_customer
        FOREIGN KEY (customer_id) REFERENCES customer_profile (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
